// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240324202802_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyApplication.Models.GodzinyPracy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CzyPraca")
                        .HasColumnType("boolean");

                    b.Property<string?>("DataAktywnosci")
                        .HasColumnType("date");

                    b.Property<string?>("DataWpisu")
                        .HasColumnType("date");

                    b.Property<int?>("IleGodzin")
                        .HasColumnType("integer");

                    b.Property<string>("NazwaProjektu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RaportGodzinPracy");
                });

            modelBuilder.Entity("MyApplication.Models.Kontrakt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresZleceniodawcy")
                        .HasColumnType("text");

                    b.Property<bool?>("CzyOutsourcing")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CzyTerminowy")
                        .HasColumnType("boolean");

                    b.Property<string?>("DataWpisu")
                        .HasColumnType("date");

                    b.Property<string>("EmailZleceniodawcy")
                        .HasColumnType("text");

                    b.Property<string>("KodPocztowyZleceniodawcy")
                        .HasColumnType("text");

                    b.Property<string?>("KoniecKontraktu")
                        .HasColumnType("date");

                    b.Property<string>("KrajZleceniodawcy")
                        .HasColumnType("text");

                    b.Property<string>("MiastoZleceniodawcy")
                        .HasColumnType("text");

                    b.Property<string>("NazwaProjektu")
                        .HasColumnType("text");

                    b.Property<string>("NazwaZleceniodawcy")
                        .HasColumnType("text");

                    b.Property<string>("NipZleceniodawcy")
                        .HasColumnType("text");

                    b.Property<string>("OpisStanowiska")
                        .HasColumnType("text");

                    b.Property<string>("Stanowisko")
                        .HasColumnType("text");

                    b.Property<string?>("StartKontraktu")
                        .HasColumnType("date");

                    b.Property<decimal?>("StawkaGodzinowa")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("StawkaMiesieczna")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Kontrakty");
                });

            modelBuilder.Entity("MyApplication.Models.Koszt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string?>("DataWystawieniaFaktury")
                        .HasColumnType("date");

                    b.Property<string>("NipFirmy")
                        .HasColumnType("text");

                    b.Property<string>("NumerFaktury")
                        .HasColumnType("text");

                    b.Property<string>("OpisKosztu")
                        .HasColumnType("text");

                    b.Property<string>("RodzajKosztu")
                        .HasColumnType("text");

                    b.Property<decimal?>("WartoscBrutto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscNetto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscVat")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Koszty");
                });

            modelBuilder.Entity("MyApplication.Models.Podatek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string?>("DataWpisu")
                        .HasColumnType("date");

                    b.Property<int?>("Miesiac")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PitDoZaplaty")
                        .HasColumnType("numeric");

                    b.Property<int?>("Rok")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VatDoOdliczenia")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("VatDoZaplaty")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ZusDoZaplaty")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Podatek");
                });

            modelBuilder.Entity("MyApplication.Models.Przychod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string?>("DataWystawieniaFaktury")
                        .HasColumnType("date");

                    b.Property<string>("NipKlienta")
                        .HasColumnType("text");

                    b.Property<string>("NumerFaktury")
                        .HasColumnType("text");

                    b.Property<string>("OpisFaktury")
                        .HasColumnType("text");

                    b.Property<string?>("TerminPlatnosci")
                        .HasColumnType("date");

                    b.Property<decimal?>("WartoscBrutto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscNetto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscVat")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Przychody");
                });

            modelBuilder.Entity("MyApplication.Models.ZestawienieGodzinPracy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string?>("DataWpisu")
                        .HasColumnType("date");

                    b.Property<int?>("IleGodzin")
                        .HasColumnType("integer");

                    b.Property<int?>("Miesiac")
                        .HasColumnType("integer");

                    b.Property<string>("NazwaProjektu")
                        .HasColumnType("text");

                    b.Property<int?>("Rok")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ZestawienieGodzinPracy");
                });

            modelBuilder.Entity("MyApplication.Models.ZestawienieMiesieczneFirmy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string?>("DataWpisu")
                        .HasColumnType("date");

                    b.Property<decimal?>("KosztyAuto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("KosztyBiuro")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("KosztyLacznie")
                        .HasColumnType("numeric");

                    b.Property<int?>("Miesiac")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrzychodyLacznie")
                        .HasColumnType("numeric");

                    b.Property<int?>("Rok")
                        .HasColumnType("integer");

                    b.Property<decimal?>("VatLacznie")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ZestawienieMiesieczneFirmy");
                });
#pragma warning restore 612, 618
        }
    }
}
