// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240308193023_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyApplication.Models.Koszty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataWystawieniaFaktury")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NipFirmy")
                        .HasColumnType("text");

                    b.Property<string>("NumerFaktury")
                        .HasColumnType("text");

                    b.Property<string>("OpisKosztu")
                        .HasColumnType("text");

                    b.Property<string>("RodzajKosztu")
                        .HasColumnType("text");

                    b.Property<decimal?>("WartoscBrutto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscNetto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscVat")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Koszty");
                });

            modelBuilder.Entity("MyApplication.Models.Przychody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataWystawieniaFaktury")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NipKlienta")
                        .HasColumnType("text");

                    b.Property<string>("NumerFaktury")
                        .HasColumnType("text");

                    b.Property<string>("OpisFaktury")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TerminPlatnosci")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("WartoscBrutto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscNetto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WartoscVat")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Przychody");
                });
#pragma warning restore 612, 618
        }
    }
}
